export const SAVE_SCORE_REQUEST = 'SAVE_SCORE_REQUEST';
export const FETCH_SCORE_REQUEST = 'FETCH_SCORE_REQUEST';
export const UPDATE_SCORE_REQUEST = 'UPDATE_SCORE_REQUEST';
export const DELETE_SCORE_REQUEST = 'DELETE_SCORE_REQUEST';
export const SCORE_SUCCESS = 'SCORE_SUCCESS';
export const SCORE_FAILURE = 'SCORE_FAILURE';
