export const SAVE_GRADE_REQUEST = 'SAVE_GRADE_REQUEST';
export const FETCH_GRADE_REQUEST = 'FETCH_GRADE_REQUEST';
export const UPDATE_GRADE_REQUEST = 'UPDATE_GRADE_REQUEST';
export const DELETE_GRADE_REQUEST = 'DELETE_GRADE_REQUEST';
export const GRADE_SUCCESS = 'GRADE_SUCCESS';
export const GRADE_FAILURE = 'GRADE_FAILURE';
