export const SAVE_SUBJECT_REQUEST = 'SAVE_SUBJECT_REQUEST';
export const FETCH_SUBJECT_REQUEST = 'FETCH_SUBJECT_REQUEST';
export const UPDATE_SUBJECT_REQUEST = 'UPDATE_SUBJECT_REQUEST';
export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST';
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE';
