export const SAVE_EXAM_REQUEST = 'SAVE_EXAM_REQUEST';
export const FETCH_EXAM_REQUEST = 'FETCH_EXAM_REQUEST';
export const UPDATE_EXAM_REQUEST = 'UPDATE_EXAM_REQUEST';
export const DELETE_EXAM_REQUEST = 'DELETE_EXAM_REQUEST';
export const EXAM_SUCCESS = 'EXAM_SUCCESS';
export const EXAM_FAILURE = 'EXAM_FAILURE';
